export const baseURL = 'http://localhost:6543';

export const STORE_KEY = {
	DOMAIN: 'STORE_DOMAIN',
	LANGUAGE_CODES: 'STORE_LANGUAGE_CODES',
	PROJECT_ID: 'STORE_PROJECT_ID',
	PRESET: 'STORE_PRESET',
	SELECT_MODE: 'STORE_SELECT_MODE',
	AUTO_SELECT_MODE: 'STORE_AUTO_SELECT_MODE',
};

// TextPluginData

export const NODE_STORE_KEY = {
	/** baseNodeId 로 써도 될듯? 이라고.... */
	LOCATION: 'NODE_LOCATION',
	LOCALIZATION_KEY: 'NODE_LOCALIZATION_KEY',
	ORIGINAL_LOCALIZE_ID: 'NODE_ORIGINAL_LOCALIZE_ID',
	/** 섹션 용 */
	SECTION: 'NODE_SECTION',
	IGNORE: 'NODE_IGNORE',
	DOMAIN_ID: 'NODE_DOMAIN_ID',
	ACTION: 'NODE_ACTION',
	// 스타일 변경 시 초기화 해야함? 그럴거면 안두는게 맞을지도? 하지만 최소한의 연산을 위해 필요하긴 함
	// 손 댔으면 변한 것이다 라는 것을 전재로 두면 쓸만함 근데 불가능함
	// 이유는 스타일 데이터는 몇개든 될 수 있음
	// STYLE: 'NODE_STYLE',
	// EFFECT: 'NODE_EFFECT',
	MODIFIER: 'NODE_MODIFIER',
};

export const BACKGROUND_STORE_KEY = {
	background: 'IS_BACKGROUND',
	// idStore: 'BACKGROUND_ID_STORE',
	data: 'METADATA',
};

export const CLIENT_STORE_KEY = {
	USER_HASH: 'CLIENT_USER_HASH',
};

export const AUTO_SELECT_MODE_PAIR = {
	REQUEST_KEY: 'AUTO_SELECT_MODE_REQUEST',
	RESPONSE_KEY: 'AUTO_SELECT_MODE_RESPONSE',
};

export const SET_USER_HASH_PAIR = {
	REQUEST_KEY: 'SET_USER_HASH_PAIR',
	RESPONSE_KEY: 'SET_USER_HASH_PAIR_RESPONSE',
};

export const GET_USER_HASH_PAIR = {
	REQUEST_KEY: 'GET_USER_HASH_PAIR',
	RESPONSE_KEY: 'GET_USER_HASH_PAIR_RESPONSE',
};

export const VARIABLE_PREFIX = 'VARIABLE_';
export const PAGE_LOCK_KEY = 'OPEN_TRANSLATION';

// Setting

export const GET_DOMAIN_PAIR = {
	REQUEST_KEY: 'GET_DOMAIN_SETTING',
	RESPONSE_KEY: 'GET_DOMAIN_SETTING_RESPONSE',
};

export const SET_DOMAIN_PAIR = {
	REQUEST_KEY: 'SET_DOMAIN_SETTING',
	RESPONSE_KEY: 'SET_DOMAIN_SETTING_RESPONSE',
};

export const GET_LANGUAGE_CODES = {
	REQUEST_KEY: 'GET_LANGUAGE_CODES',
	RESPONSE_KEY: 'GET_LANGUAGE_CODES_RESPONSE',
};

export const SET_LANGUAGE_CODES = {
	REQUEST_KEY: 'SET_LANGUAGE_CODES',
	RESPONSE_KEY: 'SET_LANGUAGE_CODES_RESPONSE',
};
// Label

export const GET_CURSOR_POSITION = {
	REQUEST_KEY: 'GET_CURSOR_POSITION_REQUEST',
	RESPONSE_KEY: 'GET_CURSOR_POSITION_RESPONSE',
};

export const SET_CURSOR_POSITION = {
	REQUEST_KEY: 'SET_CURSOR_POSITION_REQUEST',
};

export const GET_PROJECT_ID = {
	REQUEST_KEY: 'GET_PROJECT_ID_REQUEST',
	RESPONSE_KEY: 'GET_PROJECT_ID_RESPONSE',
};

export const SET_PROJECT_ID = {
	REQUEST_KEY: 'SET_PROJECT_ID_REQUEST',
	RESPONSE_KEY: 'SET_PROJECT_ID_RESPONSE',
};

export const SET_NODE_LOCATION = {
	REQUEST_KEY: 'SET_NODE_LOCATION_REQUEST',
	RESPONSE_KEY: 'SET_NODE_LOCATION_RESPONSE',
};

export const SET_NODE_LOCALIZATION_KEY = {
	REQUEST_KEY: 'SET_NODE_LOCALIZATION_KEY_REQUEST',
	RESPONSE_KEY: 'SET_NODE_LOCALIZATION_KEY_RESPONSE',
};

export const SET_NODE_ORIGINAL_LOCALIZE_ID = {
	REQUEST_KEY: 'SET_NODE_ORIGINAL_LOCALIZE_ID_REQUEST',
	RESPONSE_KEY: 'SET_NODE_ORIGINAL_LOCALIZE_ID_RESPONSE',
};

export const RELOAD_NODE = {
	REQUEST_KEY: 'RELOAD_NODE_REQUEST',
	RESPONSE_KEY: 'RELOAD_NODE_RESPONSE',
};

export const GET_LOCALIZATION_KEY_VALUE = {
	REQUEST_KEY: 'GET_LOCALIZATION_KEY_VALUE_REQUEST',
	RESPONSE_KEY: 'GET_LOCALIZATION_KEY_VALUE_RESPONSE',
};
export const SET_NODE_RESET_KEY = {
	REQUEST_KEY: 'SET_NODE_RESET_KEY_REQUEST',
	RESPONSE_KEY: 'SET_NODE_RESET_KEY_RESPONSE',
};

export const GET_TRANSLATION_KEY_VALUE = {
	REQUEST_KEY: 'GET_TRANSLATION_KEY_VALUE_REQUEST',
	RESPONSE_KEY: 'GET_TRANSLATION_KEY_VALUE_RESPONSE',
};

export const PUT_LOCALIZATION_KEY = {
	REQUEST_KEY: 'PUT_LOCALIZATION_KEY_REQUEST',
	RESPONSE_KEY: 'PUT_LOCALIZATION_KEY_RESPONSE',
};

export const UPDATE_NODE_STORE_KEY = {
	REQUEST_KEY: 'UPDATE_NODE_STORE_KEY_REQUEST',
	RESPONSE_KEY: 'UPDATE_NODE_STORE_KEY_RESPONSE',
};

export const CURRENT_SECTION_SELECTED = {
	REQUEST_KEY: 'CURRENT_SECTION_SELECTED_REQUEST',
	RESPONSE_KEY: 'CURRENT_SECTION_SELECTED_RESPONSE',
};

export const CHANGE_LANGUAGE_CODE = {
	REQUEST_KEY: 'CHANGE_LANGUAGE_CODE_REQUEST',
	RESPONSE_KEY: 'CHANGE_LANGUAGE_CODE_RESPONSE',
};

export const GET_PATTERN_MATCH_KEY = {
	REQUEST_KEY: 'GET_PATTERN_MATCH_KEY_REQUEST',
	RESPONSE_KEY: 'GET_PATTERN_MATCH_KEY_RESPONSE',
};

export const SET_NODE_LOCALIZATION_KEY_BATCH = {
	REQUEST_KEY: 'SET_NODE_LOCALIZATION_KEY_BATCH_REQUEST',
	RESPONSE_KEY: 'SET_NODE_LOCALIZATION_KEY_BATCH_RESPONSE',
};

export const UPDATE_NODE_LOCALIZATION_KEY_BATCH = {
	REQUEST_KEY: 'UPDATE_NODE_LOCALIZATION_KEY_BATCH_REQUEST',
	RESPONSE_KEY: 'UPDATE_NODE_LOCALIZATION_KEY_BATCH_RESPONSE',
};

export const SET_NODE_IGNORE = {
	REQUEST_KEY: 'SET_NODE_IGNORE_REQUEST',
	RESPONSE_KEY: 'SET_NODE_IGNORE_RESPONSE',
};

export const SET_STYLE = {
	REQUEST_KEY: 'SET_STYLE_REQUEST',
	RESPONSE_KEY: 'SET_STYLE_RESPONSE',
};

export const DOWNLOAD_STYLE = {
	REQUEST_KEY: 'DOWNLOAD_STYLE_REQUEST',
	RESPONSE_KEY: 'DOWNLOAD_STYLE_RESPONSE',
};

export const GET_STYLE_DATA = {
	REQUEST_KEY: 'GET_STYLE_DATA_REQUEST',
	RESPONSE_KEY: 'GET_STYLE_DATA_RESPONSE',
};

export const UPDATE_STYLE_DATA = {
	REQUEST_KEY: 'UPDATE_STYLE_DATA_REQUEST',
	RESPONSE_KEY: 'UPDATE_STYLE_DATA_RESPONSE',
};

export const GET_VARIABLE_DATA = {
	REQUEST_KEY: 'GET_VARIABLE_DATA_REQUEST',
	RESPONSE_KEY: 'GET_VARIABLE_DATA_RESPONSE',
};

export const SET_VARIABLE_DATA = {
	REQUEST_KEY: 'SET_VARIABLE_DATA_REQUEST',
	RESPONSE_KEY: 'SET_VARIABLE_DATA_RESPONSE',
};

export const CLEAR_VARIABLE_DATA = {
	REQUEST_KEY: 'CLEAR_VARIABLE_DATA_REQUEST',
	RESPONSE_KEY: 'CLEAR_VARIABLE_DATA_RESPONSE',
};

export const GET_PROCESS_PAIR = {
	REQUEST_KEY: 'GET_PROCESS_REQUEST',
	RESPONSE_KEY: 'GET_PROCESS_RESPONSE',
};

export const SET_PAGE_LOCK_OPEN = {
	REQUEST_KEY: 'SET_PAGE_LOCK_OPEN_REQUEST',
	RESPONSE_KEY: 'SET_PAGE_LOCK_OPEN_RESPONSE',
};

export const SET_NODE_ACTION = {
	REQUEST_KEY: 'SET_NODE_ACTION_REQUEST',
	RESPONSE_KEY: 'SET_NODE_ACTION_RESPONSE',
};

export const SET_PRESET = {
	REQUEST_KEY: 'SET_PRESET_REQUEST',
	RESPONSE_KEY: 'SET_PRESET_RESPONSE',
};

export const GET_PRESET = {
	REQUEST_KEY: 'GET_PRESET_REQUEST',
	RESPONSE_KEY: 'GET_PRESET_RESPONSE',
};

/**
 * 자동 선택 후 선택 된 노드 정보
 */
export const AUTO_SELECT_NODE_EMIT = {
	RESPONSE_KEY: 'AUTO_SELECT_NODE_EMIT_RESPONSE',
};

/**
 * 자동 선택 후 선택 된 노드 스타일 정보
 */
export const AUTO_SELECT_STYLE_EMIT = {
	RESPONSE_KEY: 'AUTO_SELECT_STYLE_EMIT_RESPONSE',
};

export const BASE_KEY_INJECTION = {
	REQUEST_KEY: 'BASE_KEY_INJECTION_REQUEST',
	RESPONSE_KEY: 'BASE_KEY_INJECTION_RESPONSE',
};

export const UPDATE_BASE_NODE = {
	REQUEST_KEY: 'UPDATE_BASE_NODE_REQUEST',
	RESPONSE_KEY: 'UPDATE_BASE_NODE_RESPONSE',
};

/**
 * store update
 */

export const SEARCH_STORE_LOCATION_EMIT = {
	RESPONSE_KEY: 'SEARCH_STORE_LOCATION_EMIT_RESPONSE',
};

export const RENDER_PAIR = {
	RENDER_REQUEST: 'RENDER_REQUEST',
	RENDER_RESPONSE: 'RENDER_RESPONSE',
};

export const DISABLE_RENDER_PAIR = {
	DISABLE_RENDER_REQUEST: 'DISABLE_RENDER_REQUEST',
	DISABLE_RENDER_RESPONSE: 'DISABLE_RENDER_RESPONSE',
};

export const RENDER_MODE_STATE = {
	/**
	 * 선택 된 걸로 오버라이드 개념만 있어서 없어도 될 듯하긴 하지만?
	 * 선택 시 바로바로 활성화 시켜주는 용도로 쓰려면 있는게 좋을지도?
	 */
	SECTION_SELECT: 'SECTION_SELECT_MODE',
	/**
	 * 멀티 키 선택 시 일관적이게 선택되는 모드
	 */
	MULTI_KEY_SELECT: 'MULTI_KEY_SELECT_MODE',
	/**
	 * 베이스 키 선택 시 하나만 선택 되게 하는 모드
	 */
	BASE_KEY_SELECT: 'BASE_KEY_SELECT_MODE',
};
/** 각 트리거는 다른 모드들을 비활성화하고 단일 대상을 활성화 하는데 사용된다 */

export const RENDER_TRIGGER = {
	SECTION_SELECT: 'SECTION_SELECT_ACCEPT',
	MULTI_KEY_SELECT: 'MULTI_KEY_SELECT_ACCEPT',
	BASE_KEY_SELECT: 'BASE_KEY_SELECT_ACCEPT',
	SAVE_ACCEPT: 'SAVE_ACCEPT',
	SAVE_ACTION: 'SAVE_ACTION',
};
/** 저장 액션 안하면 취소임 */

export const SAVE_ACTION = {
	/** 삽입 */
	INSERT: 'INSERT',
	/** 합집합 */
	UNION: 'UNION',
	/** 차집합 */
	SUBTRACT: 'SUBTRACT',
} as const;
