export const STORE_KEY = {
	DOMAIN: 'STORE_DOMAIN',
	LANGUAGE_CODES: 'STORE_LANGUAGE_CODES',
	CURSOR: 'STORE_CURSOR',
	PROJECT_ID: 'STORE_PROJECT_ID',
}

export const GET_DOMAIN_PAIR = {
	REQUEST_KEY: 'GET_DOMAIN_SETTING',
	RESPONSE_KEY: 'GET_DOMAIN_SETTING_RESPONSE',
}

export const SET_DOMAIN_PAIR = {
	REQUEST_KEY: 'SET_DOMAIN_SETTING',
	RESPONSE_KEY: 'SET_DOMAIN_SETTING_RESPONSE',
}

export const GET_LANGUAGE_CODES = {
	REQUEST_KEY: 'GET_LANGUAGE_CODES',
	RESPONSE_KEY: 'GET_LANGUAGE_CODES_RESPONSE',
}

export const SET_LANGUAGE_CODES = {
	REQUEST_KEY: 'SET_LANGUAGE_CODES',
	RESPONSE_KEY: 'SET_LANGUAGE_CODES_RESPONSE',
}

export const GET_CURSOR_POSITION = {
	REQUEST_KEY: 'GET_CURSOR_POSITION_REQUEST',
	RESPONSE_KEY: 'GET_CURSOR_POSITION_RESPONSE',
}

export const SET_CURSOR_POSITION = {
	REQUEST_KEY: 'SET_CURSOR_POSITION_REQUEST',
}

export const GET_PROJECT_ID = {
	REQUEST_KEY: 'GET_PROJECT_ID_REQUEST',
	RESPONSE_KEY: 'GET_PROJECT_ID_RESPONSE',
}

export const SET_PROJECT_ID = {
	REQUEST_KEY: 'SET_PROJECT_ID_REQUEST',
	RESPONSE_KEY: 'SET_PROJECT_ID_RESPONSE',
}
