export const STORE_KEY = {
	DOMAIN: 'STORE_DOMAIN',
	LANGUAGE_CODES: 'STORE_LANGUAGE_CODES',
}

export const GET_DOMAIN_PAIR = {
	REQUEST_KEY: 'GET_DOMAIN_SETTING',
	RESPONSE_KEY: 'GET_DOMAIN_SETTING_RESPONSE',
}

export const SET_DOMAIN_PAIR = {
	REQUEST_KEY: 'SET_DOMAIN_SETTING',
	RESPONSE_KEY: 'SET_DOMAIN_SETTING_RESPONSE',
}

export const GET_LANGUAGE_CODES = {
	REQUEST_KEY: 'GET_LANGUAGE_CODES',
	RESPONSE_KEY: 'GET_LANGUAGE_CODES_RESPONSE',
}

export const SET_LANGUAGE_CODES = {
	REQUEST_KEY: 'SET_LANGUAGE_CODES',
	RESPONSE_KEY: 'SET_LANGUAGE_CODES_RESPONSE',
}
