/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/sections': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetSections']
		put?: never
		post: operations['CreateSection']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/sections/{name}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** @description 검색으로 동작해야한다고 생각하고 도메인 이름은 수정될 수도 있다고 생각함 그래서 아이디를 사용함</br>
		 *     도메인 이름을 키로 쓰지 않으니까 유지하기로 함</br>
		 *     section 이름은 수정 불가 */
		get: operations['GetSection']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/sections/id/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** @description 검색으로 동작해야한다고 생각하고 도메인 이름은 수정될 수도 있다고 생각함 그래서 아이디를 사용함</br>
		 *     도메인 이름을 키로 쓰지 않으니까 유지하기로 함</br>
		 *     section 이름은 수정 불가 */
		get: operations['GetSectionById']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/sections/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		/** @description 문서 정보 변경 */
		put: operations['UpdateSection']
		post?: never
		delete: operations['DeleteSection']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/sections/{id}/keys': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** @description 섹션에 속한 로컬라이제이션 키 목록을 조회합니다. */
		get: operations['GetKeysBySection']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/resources': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetResources']
		put?: never
		post: operations['CreateResource']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/resources/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetResource']
		put: operations['UpdateResource']
		post?: never
		delete: operations['DeleteResource']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/resources/{id}/keys': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetKeysByResource']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/keys/all': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** 전체 키 리스트 조회 */
		get: operations['GetKeys']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/keys': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** 도메인 내 키 리스트 조회 */
		get: operations['GetKeysByDomain']
		put?: never
		/** 키 생성 */
		post: operations['CreateKey']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/keys/section/{sectionId}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** 도메인 내 섹션 내 키 리스트 조회 */
		get: operations['GetKeysByDomainAndSection']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/keys/name/{name}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** 이름으로 검색 */
		get: operations['GetKeyByNameSearch']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/keys/id/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetKeyById']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/keys/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		/** 변수나 스타일에 대한 키 수정 */
		put: operations['UpdateKey']
		post?: never
		/**
		 * 키 삭제
		 * @description 하위 키 삭제 같이 해야 함
		 */
		delete: operations['DeleteKey']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/keys/{id}/translations': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** 키 번역 목록 조회 */
		get: operations['GetTranslationsByKey']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/keys/by-temporary-name/{tempName}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * 임시 키 이름으로 현재 키 검색
		 * @description 보통 아이디로 임시 값 검색하는데 저장된 아이디가 없을 때 사용
		 */
		get: operations['FindKeyByTemporaryName']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/translations': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetTranslations']
		/** @description 있으면 수정하고 없으면 추가함 */
		put: operations['UpdateTranslation']
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/translations/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetTranslationById']
		put?: never
		post?: never
		/**
		 * @deprecated
		 * @description 번역 삭제 인데..? 굳이 삭제 안하고 공백처리만 해도 무방하다~
		 */
		delete: operations['DeleteTranslation']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/localization/translations/search': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** @description 키 ID와 언어 코드로 번역 검색 */
		post: operations['SearchTranslation']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/figma/locations': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetLocations']
		put?: never
		/** @description 피그마 위치를 식별하는 키 생성</br>
		 *     완전히 겹치면 추가할 필요 없으니 있는 값 반환함 */
		post: operations['CreateLocation']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/figma/locations/{nodeId}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/**
		 * @deprecated
		 * @description 쓸 일 없어서 설계 안함
		 */
		get: operations['GetLocation']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/figma/locations/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		/** @deprecated */
		put: operations['UpdateLocation']
		post?: never
		delete: operations['DeleteLocation']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/figma/locations/mapping': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** @description 로컬라이제이션 키와 피그마 위치를 매핑함 */
		post: operations['CreateMapping']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/figma/locations/mapping/{keyId}/{locationId}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		delete: operations['DeleteMapping']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/domains': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetDomains']
		put?: never
		post: operations['CreateDomain']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/domains/{name}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetDomain']
		put: operations['UpdateDomain']
		post?: never
		delete: operations['DeleteDomain']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/domains/{name}/sections': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['GetSectionsByDomain']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/domains/{name}/languages': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** @description 도메인의 언어 코드 목록을 조회합니다. */
		get: operations['GetDomainLanguages']
		/** @description 도메인에 새로운 언어를 추가합니다. */
		put: operations['UpdateDomainLanguages']
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/domains/{name}/languages/{languageCode}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		/** @description 도메인에서 특정 언어를 제거합니다. */
		delete: operations['RemoveDomainLanguage']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/register': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** 사용자 등록 */
		post: operations['Register']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/validate': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		/** 사용자 인증 검증 */
		post: operations['Validate']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/refresh-hash': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['RefreshHash']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/{username}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		/** 사용자 정보 조회 */
		get: operations['GetUser']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/auth/username': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		/** 사용자 이름 변경 */
		put: operations['UpdateUsername']
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		Section: {
			/** Format: double */
			section_id: number
			/** Format: double */
			domain_id: number
			section_name: string
			doc_link?: string
			created_at: string
			updated_at: string
		}
		CreateSectionDTO: {
			name: string
			domainId: string
			link: string
		}
		UpdateSectionDTO: {
			link?: string
		}
		LocalizationKey: {
			/** Format: double */
			key_id: number
			/** Format: double */
			domain_id: number
			name: string
			alias: string | null
			/** Format: double */
			parent_key_id: number | null
			is_variable: boolean
			is_temporary: boolean
			/** Format: double */
			section_id: number | null
			/** Format: double */
			version: number
			is_deleted: boolean
			created_at: string
			updated_at: string
			domain_name: string
			section_name: string | null
			/** Format: double */
			translation_count: number
			translated_languages: string[]
		}
		CreateResourceDTO: {
			name: string
			type: string
		}
		UpdateResourceDTO: {
			name?: string
			type?: string
		}
		LocalizationKeyDetail: {
			/** Format: double */
			key_id: number
			name: string
			/** Format: double */
			domain_id: number
			domain_name: string
			/** Format: double */
			section_id: number | null
			section_name: string | null
			/**
			 * Format: double
			 * @description 변수 정의나 스타일 키를 정의하게 되면 부모 키가 생성되는데, 이 때 부모 키의 ID가 저장됩니다.
			 */
			parent_key_id: number | null
			/** @description 키가 변수 키라면 true 로 설정
			 *     변수 키는 로컬라이제이션 텍스트가 없어도 됨 */
			is_variable: boolean
			created_at: string
			updated_at: string
		}
		CreateLocalizationKeyDTO: {
			/**
			 * Format: double
			 * @description 도메인 ID
			 */
			domainId: number
			/** @description 키 이름 */
			name: string
			/** @description 키 별칭 (optional) */
			alias?: string
			/**
			 * Format: double
			 * @description 부모 키 ID (optional)
			 */
			parentKeyId?: number
			/** @description 변수 포함 여부 (optional) */
			isVariable?: boolean
			/** @description 임시 키 여부 (optional) */
			isTemporary?: boolean
			/**
			 * Format: double
			 * @description 섹션 ID (optional)
			 */
			sectionId?: number
		}
		UpdateLocalizationKeyDTO: {
			name?: string
			domainId?: string
			alias?: string
			parentKeyId?: string
			isVariable?: boolean
			isTemporary?: boolean
			sectionId?: string
			/** Format: double */
			version?: number
			isDeleted?: boolean
		}
		Localization: {
			/** Format: double */
			localization_id: number
			/** Format: double */
			key_id: number
			language_code: string
			text: string
			created_at: string
			updated_at: string
		}
		CreateTranslationDTO: {
			keyId: string
			language: string
			translation: string
		}
		FigmaLocation: {
			/** Format: double */
			location_id: number
			/** @description 피그마 프로젝트 ID */
			project_id: string
			/** @description 피그마 페이지 ID */
			page_id: string
			/** @description 피그마 노드 ID */
			node_id: string
			is_pinned: boolean
			created_at: string
			updated_at: string
		}
		CreateFigmaLocationDTO: {
			projectId: string
			pageId: string
			nodeId: string
			isPinned?: boolean
		}
		UpdateFigmaLocationDTO: {
			projectId?: string
			pageId?: string
			nodeId?: string
			isPinned?: boolean
		}
		Domain: {
			/** Format: double */
			domain_id: number
			domain_name: string
			language_codes: string[]
			created_at: string
			updated_at: string
		}
		CreateDomainDTO: {
			domain: string
		}
		UpdateDomainDTO: {
			domain?: string
		}
		UpdateDomainLanguagesDTO: {
			/**
			 * @description 추가할 언어 코드 배열
			 * @example [
			 *       "en",
			 *       "ja"
			 *     ]
			 */
			languageCodes: string[]
		}
		UserResponse: {
			/** Format: double */
			user_id: number
			username: string
		}
		RegisterDTO: {
			username: string
			password: string
		}
		ValidateDTO: {
			username: string
			password_hash: string
		}
		UpdateUsernameDTO: {
			currentUsername: string
			password_hash: string
			newUsername: string
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	GetSections: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Section'][]
				}
			}
		}
	}
	CreateSection: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateSectionDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Section']
				}
			}
		}
	}
	GetSection: {
		parameters: {
			query?: never
			header: {
				'X-Domain-Id': string
			}
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Section']
				}
			}
		}
	}
	GetSectionById: {
		parameters: {
			query?: never
			header: {
				'X-Domain-Id': string
			}
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Section']
				}
			}
		}
	}
	UpdateSection: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateSectionDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Section']
				}
			}
		}
	}
	DeleteSection: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	GetKeysBySection: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description - 섹션 ID (0인 경우 section_id가 NULL인 키들을 조회) */
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description 로컬라이제이션 키 목록 */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['LocalizationKey'][]
				}
			}
		}
	}
	GetResources: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': unknown
				}
			}
		}
	}
	CreateResource: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateResourceDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': unknown
				}
			}
		}
	}
	GetResource: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': unknown
				}
			}
		}
	}
	UpdateResource: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateResourceDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': unknown
				}
			}
		}
	}
	DeleteResource: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	GetKeysByResource: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': unknown
				}
			}
		}
	}
	GetKeys: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': unknown
				}
			}
		}
	}
	GetKeysByDomain: {
		parameters: {
			query?: never
			header: {
				'X-Domain-Id': string
			}
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['LocalizationKeyDetail']
				}
			}
		}
	}
	CreateKey: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateLocalizationKeyDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': unknown
				}
			}
		}
	}
	GetKeysByDomainAndSection: {
		parameters: {
			query?: never
			header: {
				'X-Domain-Id': string
			}
			path: {
				sectionId: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['LocalizationKeyDetail']
				}
			}
		}
	}
	GetKeyByNameSearch: {
		parameters: {
			query?: never
			header: {
				'X-Domain-Id': string
			}
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['LocalizationKeyDetail']
				}
			}
		}
	}
	GetKeyById: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['LocalizationKeyDetail']
				}
			}
		}
	}
	UpdateKey: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateLocalizationKeyDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': unknown
				}
			}
		}
	}
	DeleteKey: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	GetTranslationsByKey: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': unknown
				}
			}
		}
	}
	FindKeyByTemporaryName: {
		parameters: {
			query?: never
			header?: never
			path: {
				tempName: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['LocalizationKeyDetail']
				}
			}
		}
	}
	GetTranslations: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Localization'][]
				}
			}
		}
	}
	UpdateTranslation: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateTranslationDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Localization']
				}
			}
		}
	}
	GetTranslationById: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Localization']
				}
			}
		}
	}
	DeleteTranslation: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	SearchTranslation: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': {
					language: string
					keyId: string
				}
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Localization'] | null
				}
			}
		}
	}
	GetLocations: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['FigmaLocation'][]
				}
			}
		}
	}
	CreateLocation: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateFigmaLocationDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['FigmaLocation']
				}
			}
		}
	}
	GetLocation: {
		parameters: {
			query?: never
			header?: never
			path: {
				nodeId: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['FigmaLocation']
				}
			}
		}
	}
	UpdateLocation: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateFigmaLocationDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['FigmaLocation']
				}
			}
		}
	}
	DeleteLocation: {
		parameters: {
			query?: never
			header?: never
			path: {
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	CreateMapping: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': {
					locationId: string
					keyId: string
				}
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': unknown
				}
			}
		}
	}
	DeleteMapping: {
		parameters: {
			query?: never
			header?: never
			path: {
				keyId: string
				locationId: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	GetDomains: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Domain'][]
				}
			}
		}
	}
	CreateDomain: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateDomainDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Domain']
				}
			}
		}
	}
	GetDomain: {
		parameters: {
			query?: never
			header?: never
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Domain']
				}
			}
		}
	}
	UpdateDomain: {
		parameters: {
			query?: never
			header?: never
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateDomainDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Domain']
				}
			}
		}
	}
	DeleteDomain: {
		parameters: {
			query?: never
			header?: never
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	GetSectionsByDomain: {
		parameters: {
			query?: never
			header?: never
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['Section'][]
				}
			}
		}
	}
	GetDomainLanguages: {
		parameters: {
			query?: never
			header?: never
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': string[]
				}
			}
		}
	}
	UpdateDomainLanguages: {
		parameters: {
			query?: never
			header?: never
			path: {
				name: string
			}
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateDomainLanguagesDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': string[]
				}
			}
		}
	}
	RemoveDomainLanguage: {
		parameters: {
			query?: never
			header?: never
			path: {
				name: string
				languageCode: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	Register: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['RegisterDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['UserResponse']
				}
			}
		}
	}
	Validate: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['ValidateDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						isValid: boolean
					}
				}
			}
		}
	}
	RefreshHash: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['ValidateDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': {
						new_hash?: string
						isSuccess: boolean
					}
				}
			}
		}
	}
	GetUser: {
		parameters: {
			query?: never
			header?: never
			path: {
				username: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['UserResponse']
				}
			}
		}
	}
	UpdateUsername: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateUsernameDTO']
			}
		}
		responses: {
			/** @description Ok */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['UserResponse']
				}
			}
		}
	}
}
